name: Build PyICU wheels for Windows

on:
  workflow_dispatch:

env:
  PYICU_TAG: v2.15.3
  ICU_VERSION: 77
  ICU_RELEASE: 77-1/icu4c-77_1
  CIBW_TEST_REQUIRES: pytest six
  CIBW_TEST_COMMAND: pytest {project}/test
  CIBW_BUILD: "cp311* cp312* cp313*"

jobs:
  build_amd64:
    name: Build AMD64 wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      ICU_ARCH: 64
      ICU_PLAT: Win64-MSVC2022
    steps:
      - uses: actions/checkout@v5
      - run: download.cmd
        shell: cmd
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse ./
        env:
          CIBW_ARCHS_WINDOWS: AMD64
          CIBW_ENVIRONMENT_WINDOWS: INCLUDE="include;$INCLUDE" LIB="lib$ICU_ARCH;$LIB"
      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
          name: wheels-win-amd64
